import { Message } from '../types/session';
import { TriageResult } from '../types/triage';

/**
 * Builds the prompt for incident report generation.
 * Synthesizes the triage result and conversation history into a structured report.
 */
export function buildReportPrompt(
  triageResult: TriageResult | null,
  originalInput: string | null,
  conversationHistory: Message[],
): Message[] {
  const triageJson = triageResult
    ? JSON.stringify(triageResult, null, 2)
    : 'No structured triage result available.';

  // Extract only user/assistant chat messages (not the initial triage exchange)
  const chatMessages = conversationHistory
    .filter((m) => m.role !== 'system')
    .slice(2) // skip the initial input and triage response
    .map((m) => `${m.role.toUpperCase()}: ${m.content}`)
    .join('\n\n');

  const systemPrompt = `You are a technical writer generating a clear, professional incident report suitable for an engineering team.

Generate a report using the following markdown format:

# Incident Report: [Brief Title]

## Status
[Current status: Investigating / Identified / Resolved]

## Summary
[2-3 sentence summary of the incident]

## Severity
[Severity level with brief justification]

## Timeline & Evidence
[Key observations from the provided logs/errors/input]

## Root Cause Analysis
[Most likely root cause(s) with reasoning]

## Impact Assessment
[Who/what is affected and how]

## Recommended Actions
[Numbered list of concrete actions to resolve and prevent recurrence]

## Open Questions
[Unresolved questions or areas needing further investigation]

## AI Confidence Note
[State the confidence level and any assumptions made]

---
*This report was generated by AI-assisted incident triage. All findings should be verified by the engineering team.*

Guidelines:
- Be factual and precise — only reference information from the provided context
- Distinguish between confirmed facts and inferences
- Use technical language appropriate for engineers
- Keep each section concise but actionable
- Do not fabricate details not present in the evidence`;

  const userPrompt = `Generate an incident report from the following data:

ORIGINAL INPUT:
${originalInput || 'Not available'}

TRIAGE RESULT:
${triageJson}

${chatMessages ? `FOLLOW-UP DISCUSSION:\n${chatMessages}` : 'No follow-up discussion.'}`;

  return [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];
}
